rfx9600:
  name: RFX9600 Relay Service
  description: Control relays on Philips RFX9600
  fields:
    rfx9600Ip:
      name: RFX9600 IP Address
      Description: IP Address of RFX9600
      required: true
      selector: 
        text:
    rfx9600Action:
      name: RFX9600 Action
      Description: Select the action to perform
      required: true
      selector: 
        select:
          options:
            - label: Turn Relay On
              value: "on"
            - label: Turn Relay Off
              value: "off"
            - label: Toggle Relay
              value: "toggle"
    rfx9600Relay:
      name: RFX9600 Relay
      Description: The number of the relay
      required: true
      selector: 
        number:
          min: 1
          max: 4
          mode: box

